export type { DomainIssue, DomainResult } from './domain/validation'
export type { AnswerScaffold, AnswerScaffoldInput } from './domain/answerScaffold'
export { normalizeAnswerScaffold, validateAnswerScaffold } from './domain/answerScaffold'
export type { OverlayStyle } from './domain/overlayStyle'
export { DEFAULT_OVERLAY_STYLE, normalizeOverlayStyle, validateOverlayStyle } from './domain/overlayStyle'
export type { Intent } from './domain/intent'
export { classifyIntent } from './domain/intent'
export type { OverlayPort } from './ports/overlayPort'
export type { ScaffoldRepositoryPort } from './ports/scaffoldRepository'
export type { AppSettings, SettingsRepositoryPort } from './ports/settingsRepository'
export type { LlmHintRequest, LlmHintResponse, LlmMode, LlmProviderPort } from './ports/llmProvider'
export * from './application'
